name: Build iOS 26 Unsigned IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # 指定 runner（假設 macOS-15 或最新支援 Xcode 26 的環境）
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode 26
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0"

      - name: Show Xcode & SDK info (debug)
        run: |
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-version
          xcodebuild -showsdks

      - name: Show available schemes (debug)
        run: |
          xcodebuild -list -project "Apple Intelligence Chat.xcodeproj"

      - name: Build Xcode archive (unsigned)
        run: |
          xcodebuild archive \
            -project "Apple Intelligence Chat.xcodeproj" \
            -scheme "Apple Intelligence Chat" \
            -configuration Release \
            -archivePath build/AppleIntelligenceChat.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            OTHER_CODE_SIGN_FLAGS=""

      - name: Create unsigned IPA
        run: |
          APP_NAME="Apple Intelligence Chat"
          ARCHIVE_PATH="build/AppleIntelligenceChat.xcarchive"
          OUTPUT_DIR="build"
          mkdir -p "${OUTPUT_DIR}/Payload"
          cp -r "${ARCHIVE_PATH}/Products/Applications/${APP_NAME}.app" "${OUTPUT_DIR}/Payload/"
          cd "${OUTPUT_DIR}"
          zip -r "${APP_NAME}-unsigned.ipa" Payload
          cd -

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/*.ipa

      # -- 可選 -- 同時上傳 .xcarchive 作為 artifact
      - name: Upload xcarchive artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: xcarchive
          path: build/*.xcarchive
