name: Build Unsigned IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show available schemes (debug info)
        run: |
          xcodebuild -list -project "Apple Intelligence Chat.xcodeproj"

      - name: Build Xcode archive (unsigned)
        run: |
          xcodebuild archive \
            -project "Apple Intelligence Chat.xcodeproj" \
            -scheme "Apple Intelligence Chat" \
            -configuration Release \
            -archivePath build/AppleIntelligenceChat.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            OTHER_CODE_SIGN_FLAGS=""

      - name: Create unsigned IPA
        run: |
          APP_NAME="Apple Intelligence Chat"
          ARCHIVE_PATH="build/AppleIntelligenceChat.xcarchive"
          OUTPUT_DIR="build"
          mkdir -p "${OUTPUT_DIR}/Payload"
          cp -r "${ARCHIVE_PATH}/Products/Applications/${APP_NAME}.app" "${OUTPUT_DIR}/Payload/"
          cd "${OUTPUT_DIR}"
          zip -r "${APP_NAME}-unsigned.ipa" Payload
          cd -

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/*.ipa
