name: Build Unsigned IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 若有用 CocoaPods，可解除註解
      #- name: Install CocoaPods dependencies
      #  run: |
      #    cd ios
      #    pod install
      #    cd ..

      - name: Build Xcode archive (unsigned)
        run: |
          xcodebuild archive \
            -workspace "YourApp.xcworkspace" \    # 或 -project "YourApp.xcodeproj"
            -scheme "YourApp" \
            -configuration Release \
            -archivePath build/YourApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            OTHER_CODE_SIGN_FLAGS=""

      - name: Create unsigned IPA
        run: |
          APP_NAME="YourApp"
          ARCHIVE_PATH="build/${APP_NAME}.xcarchive"
          OUTPUT_DIR="build"
          mkdir -p "${OUTPUT_DIR}/Payload"
          cp -r "${ARCHIVE_PATH}/Products/Applications/${APP_NAME}.app" "${OUTPUT_DIR}/Payload/"
          cd "${OUTPUT_DIR}"
          zip -r "${APP_NAME}-unsigned.ipa" Payload
          cd -

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/*.ipa
